language: c
compiler:
  - gcc
  - clang
# Change this to your needs
script: sh autogen.sh && ./configure && make && make check && make distcheck
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential autoconf automake libtool zlib1g zlib1g-dev make 

matrix:
    include:
        - name: fuzza
          env: CXX="clang++" ASAN_OPTIONS=detect_leaks=0 CXXFLAGS="-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address" CFLAGS="-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address" LDFLAGS="-fsanitize=address"
          compiler: clang
          os: linux
        - name: fuzzm
          env: CXX="clang++" CXXFLAGS="-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=memory" CFLAGS="-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=memory" LDFLAGS="-fsanitize=memory"
          compiler: clang
          os: linux
        - name: fuzzu
          env: CXX="clang++" CXXFLAGS="-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=undefined" CFLAGS="-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=undefined -fno-sanitize-recover=undefined,integer" LDFLAGS="-fsanitize=undefined"
          compiler: clang
          os: linux
